Cypress.on('uncaught:exception', (err, runnable) => {
  return false
})
describe('Verify Sign Up Scenario', () => {
  it('Success Sign Up New Account', () => {
    const randomUsername = Math.random().toString(36).substring(2,15)
    cy.visit('https://itera-qa.azurewebsites.net/')
    cy.get('.form-inline > .navbar-nav > :nth-child(1) > .nav-link').click()
    cy.get('#FirstName')
    .should('be.visible')
    .type('Satpam')
    cy.get('#Surname')
    .should('be.visible')
    .type('Ngehe')
    cy.get('#E_post')
    .should('be.visible')
    .type('satpamngehe@gmail.com')
    cy.get('#Mobile')
    .should('be.visible')
    .type('085655261726')
    cy.get('#Username')
    .should('be.visible')
    .type(randomUsername)
    cy.get('#Password')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#ConfirmPassword')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#submit')
    .should('be.visible')
    .click()
    cy.get('.label-success')
    .should('contain.text', 'Registration Successful')
  })

  it('Success Sign Up New Account with a Special Character in Username', () => {
    const randomUsername = Math.random().toString(36).substring(2,15)
    cy.visit('https://itera-qa.azurewebsites.net/')
    cy.get('.form-inline > .navbar-nav > :nth-child(1) > .nav-link').click()
    cy.get('#FirstName')
    .should('be.visible')
    .type('Satpam')
    cy.get('#Surname')
    .should('be.visible')
    .type('Ngehe')
    cy.get('#E_post')
    .should('be.visible')
    .type('satpamngehe@gmail.com')
    cy.get('#Mobile')
    .should('be.visible')
    .type('085655261726')
    cy.get('#Username')
    .should('be.visible')
    .type(randomUsername)
    cy.get('#Password')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#ConfirmPassword')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#submit')
    .should('be.visible')
    .click()
    cy.get('.label-success')
    .should('contain.text', 'Registration Successful')
  })

  it('Success Sign Up New Account with Existing First Name and Surname but Different Username', () => {
    const randomUsername = Math.random().toString(36).substring(2,15)+'!!@@'
    cy.visit('https://itera-qa.azurewebsites.net/')
    cy.get('.form-inline > .navbar-nav > :nth-child(1) > .nav-link').click()
    cy.get('#FirstName')
    .should('be.visible')
    .type('Satpam')
    cy.get('#Surname')
    .should('be.visible')
    .type('Ngehe')
    cy.get('#E_post')
    .should('be.visible')
    .type('satpamngehe@gmail.com')
    cy.get('#Mobile')
    .should('be.visible')
    .type('085655261726')
    cy.get('#Username')
    .should('be.visible')
    .type(randomUsername)
    cy.get('#Password')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#ConfirmPassword')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#submit')
    .should('be.visible')
    .click()
    cy.get('.label-success')
    .should('contain.text', 'Registration Successful')
  })

  it('Success Sign Up with Empty Email', () => {
    const randomUsername = Math.random().toString(36).substring(2,15)
    cy.visit('https://itera-qa.azurewebsites.net/')
    cy.get('.form-inline > .navbar-nav > :nth-child(1) > .nav-link').click()
    cy.get('#FirstName')
    .should('be.visible')
    .type('Satpam')
    cy.get('#Surname')
    .should('be.visible')
    .type('Lucu')
    cy.get('#Mobile')
    .should('be.visible')
    .type('081774153675')
    cy.get('#Username')
    .should('be.visible')
    .type(randomUsername)
    cy.get('#Password')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#ConfirmPassword')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#submit')
    .should('be.visible')
    .click()
    cy.get('.label-success')
    .should('contain.text', 'Registration Successful')
  })

  it('Success Sign Up with Empty Mobile Phone', () => {
    const randomUsername = Math.random().toString(36).substring(2,15)
    cy.visit('https://itera-qa.azurewebsites.net/')
    cy.get('.form-inline > .navbar-nav > :nth-child(1) > .nav-link').click()
    cy.get('#FirstName')
    .should('be.visible')
    .type('Satpam')
    cy.get('#Surname')
    .should('be.visible')
    .type('Kabur')
    cy.get('#E_post')
    .should('be.visible')
    .type('satpamkabur@gmail.com')
    cy.get('#Mobile')
    .should('be.visible')
    .click()
    cy.get('#Username')
    .should('be.visible')
    .type(randomUsername)
    cy.get('#Password')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#ConfirmPassword')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#submit')
    .should('be.visible')
    .click()
    cy.get('.label-success')
    .should('contain.text', 'Registration Successful')
  })

  it('Success Sign Up with Existing Email but Different Username', () => {
    const randomUsername = Math.random().toString(36).substring(2,15)
    cy.visit('https://itera-qa.azurewebsites.net/')
    cy.get('.form-inline > .navbar-nav > :nth-child(1) > .nav-link').click()
    cy.get('#FirstName')
    .should('be.visible')
    .type('Satpam')
    cy.get('#Surname')
    .should('be.visible')
    .type('Ganteng')
    cy.get('#E_post')
    .should('be.visible')
    .type('satpamkabur@gmail.com')
    cy.get('#Mobile')
    .should('be.visible')
    .type('081774153675')
    cy.get('#Username')
    .should('be.visible')
    .type(randomUsername)
    cy.get('#Password')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#ConfirmPassword')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#submit')
    .should('be.visible')
    .click()
    cy.get('.label-success')
    .should('contain.text', 'Registration Successful')
  })

  it('Failed Sign Up without Input First Name', () => {
    cy.visit('https://itera-qa.azurewebsites.net/')
    cy.get('.form-inline > .navbar-nav > :nth-child(1) > .nav-link').click()
    cy.get('#Surname')
    .should('be.visible')
    .type('Galby')
    cy.get('#E_post')
    .should('be.visible')
    .type('isyroqigalby.ig@gmail.com')
    cy.get('#Mobile')
    .should('be.visible')
    .type('081774153675')
    cy.get('#Username')
    .should('be.visible')
    .type('goyangdombret')
    cy.get('#Password')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#ConfirmPassword')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#submit')
    .should('be.visible')
    .click()
    cy.get('#FirstName-error')
    .should('contain.text', 'Please enter first name')
  })

  it('Failed Sign Up without Input Surname', () => {
    cy.visit('https://itera-qa.azurewebsites.net/')
    cy.get('.form-inline > .navbar-nav > :nth-child(1) > .nav-link').click()
    cy.get('#FirstName')
    .should('be.visible')
    .type('Kebal')
    cy.get('#E_post')
    .should('be.visible')
    .type('isyroqigalby.ig@gmail.com')
    cy.get('#Mobile')
    .should('be.visible')
    .type('081774153675')
    cy.get('#Username')
    .should('be.visible')
    .type('goyangdombret')
    cy.get('#Password')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#ConfirmPassword')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#submit')
    .should('be.visible')
    .click()
    cy.get('#Surname-error')
    .should('contain.text', 'Please enter surname')
  })

  it('Failed Sign Up with Existing Username', () => {
    cy.visit('https://itera-qa.azurewebsites.net/')
    cy.get('.form-inline > .navbar-nav > :nth-child(1) > .nav-link').click()
    cy.get('#FirstName')
    .should('be.visible')
    .type('Isyroqi')
    cy.get('#Surname')
    .should('be.visible')
    .type('Galby')
    cy.get('#E_post')
    .should('be.visible')
    .type('isyroqigalby.ig@gmail.com')
    cy.get('#Mobile')
    .should('be.visible')
    .type('081774153675')
    cy.get('#Username')
    .should('be.visible')
    .type('goyangdombret')
    cy.get('#Password')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#ConfirmPassword')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#submit')
    .should('be.visible')
    .click()
    cy.get('.label-danger')
    .should('contain.text', 'Username already exist')
  })

  it('Failed Sign Up with Empty Character in Username', () => {
    cy.visit('https://itera-qa.azurewebsites.net/')
    cy.get('.form-inline > .navbar-nav > :nth-child(1) > .nav-link').click()
    cy.get('#FirstName')
    .should('be.visible')
    .type('Isyroqi')
    cy.get('#Surname')
    .should('be.visible')
    .type('Galby')
    cy.get('#E_post')
    .should('be.visible')
    .type('isyroqigalby.ig@gmail.com')
    cy.get('#Mobile')
    .should('be.visible')
    .type('081774153675')
    cy.get('#Username')
    .should('be.visible')
    .type(' ')
    cy.get('#Password')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#ConfirmPassword')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#submit')
    .should('be.visible')
    .click()
    cy.get('h1')
    .should('contain.text', 'Error.')
    cy.get('h2')
    .should('contain.text', 'An error occurred while processing your request.')
  })

  it('Failed Sign Up without Input Username', () => {
    cy.visit('https://itera-qa.azurewebsites.net/')
    cy.get('.form-inline > .navbar-nav > :nth-child(1) > .nav-link').click()
    cy.get('#FirstName')
    .should('be.visible')
    .type('Isyroqi')
    cy.get('#Surname')
    .should('be.visible')
    .type('Galby')
    cy.get('#E_post')
    .should('be.visible')
    .type('isyroqigalby.ig@gmail.com')
    cy.get('#Mobile')
    .should('be.visible')
    .type('081774153675')
    cy.get('#Password')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#ConfirmPassword')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#submit')
    .should('be.visible')
    .click()
    cy.get('#Username-error')
    .should('contain.text', 'Please enter username')
  })

  it('Failed Sign Up without Input Password and Confirm Password', () => {
    cy.visit('https://itera-qa.azurewebsites.net/')
    cy.get('.form-inline > .navbar-nav > :nth-child(1) > .nav-link').click()
    cy.get('#FirstName')
    .should('be.visible')
    .type('Isyroqi')
    cy.get('#Surname')
    .should('be.visible')
    .type('Galby')
    cy.get('#E_post')
    .should('be.visible')
    .type('isyroqigalby.ig@gmail.com')
    cy.get('#Mobile')
    .should('be.visible')
    .type('081774153675')
    cy.get('#Username')
    .should('be.visible')
    .type('KebalHukum')
    cy.get('#submit')
    .should('be.visible')
    .click()
    cy.get('#Password-error')
    .should('contain.text', "Please enter password")
  })

  it('Failed Sign Up without Input Password', () => {
    cy.visit('https://itera-qa.azurewebsites.net/')
    cy.get('.form-inline > .navbar-nav > :nth-child(1) > .nav-link').click()
    cy.get('#FirstName')
    .should('be.visible')
    .type('Isyroqi')
    cy.get('#Surname')
    .should('be.visible')
    .type('Galby')
    cy.get('#E_post')
    .should('be.visible')
    .type('isyroqigalby.ig@gmail.com')
    cy.get('#Mobile')
    .should('be.visible')
    .type('081774153675')
    cy.get('#Username')
    .should('be.visible')
    .type('KebalHukum')
    cy.get('#ConfirmPassword')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#submit')
    .should('be.visible')
    .click()
    cy.get('#ConfirmPassword-error')
    .should('contain.text', "'Confirm password' and 'Password' do not match.")
  })

  it('Failed Sign Up without Input Confirm Password', () => {
    cy.visit('https://itera-qa.azurewebsites.net/')
    cy.get('.form-inline > .navbar-nav > :nth-child(1) > .nav-link').click()
    cy.get('#FirstName')
    .should('be.visible')
    .type('Isyroqi')
    cy.get('#Surname')
    .should('be.visible')
    .type('Galby')
    cy.get('#E_post')
    .should('be.visible')
    .type('isyroqigalby.ig@gmail.com')
    cy.get('#Mobile')
    .should('be.visible')
    .type('081774153675')
    cy.get('#Username')
    .should('be.visible')
    .click()
    cy.get('#Password')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#submit')
    .should('be.visible')
    .click()
    cy.get('#ConfirmPassword-error')
    .should('contain.text', "'Confirm password' and 'Password' do not match.")
  })

  it('Failed Sign Up New Account with a Very Long Username', () => {
    cy.visit('https://itera-qa.azurewebsites.net/')
    cy.get('.form-inline > .navbar-nav > :nth-child(1) > .nav-link').click()
    cy.get('#FirstName')
    .should('be.visible')
    .type('Satpam')
    cy.get('#Surname')
    .should('be.visible')
    .type('Ngehe')
    cy.get('#E_post')
    .should('be.visible')
    .type('satpamngehe@gmail.com')
    cy.get('#Mobile')
    .should('be.visible')
    .type('085655261726')
    cy.get('#Username')
    .should('be.visible')
    .type('54tpamngehe2!!!kjashdigsajahsuitadgsahdgasiudhoasasugdyasgidgasuidgiyadgijasdgiugasiuod')
    cy.get('#Password')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#ConfirmPassword')
    .should('be.visible')
    .type('NyobaDoangIni1')
    cy.get('#submit')
    .should('be.visible')
    .click()
    cy.get('h1')
    .should('contain.text', 'Error.')
    cy.get('h2')
    .should('contain.text', 'An error occurred while processing your request.')
  })
})